CREATE TABLE AGE
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
AGE VARCHAR(10) NOT NULL,
ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE CITY
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CITY VARCHAR(25) NOT NULL,
ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE CATEGORY
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
CATEGORY VARCHAR(40) NOT NULL,
ACTIVE INTEGER DEFAULT 1 
);

CREATE TABLE EXPERIENCE
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
EXPERIENCE VARCHAR(25) NOT NULL,
ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE EDUCATION
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
EDUCATION VARCHAR(30) NOT NULL,
ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE WORKMODE
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
WORKMODE VARCHAR(25) NOT NULL,
ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE STATUS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(25) NOT NULL,
    ACTIVE INTEGER DEFAULT 1
);

CREATE TABLE COMPANY
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
COMPANY_NAME VARCHAR(50) NOT NULL,
NAME VARCHAR(30) NOT NULL,
SURNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) UNIQUE NOT NULL,
PHONE VARCHAR(15) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
CITY_ID INTEGER NOT NULL,
ABOUT_COMPANY VARCHAR(1000),
LOGO VARCHAR(100),
DATA_DATE DATE,
ACTIVE INTEGER DEFAULT 0,
WEBSITE VARCHAR(30),
CONSTRAINT CITY_ID_FK FOREIGN KEY(CITY_ID) REFERENCES CITY(ID)
);



CREATE TABLE VACANCY
(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
VACANCY_NAME VARCHAR(100) NOT NULL,
INFORMATION VARCHAR(3000) NOT NULL,
REQUIREMENTS VARCHAR(3000) NOT NULL,
SALARY VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(100),
AGE_ID INTEGER NOT NULL,
CATEGORY_ID INTEGER NOT NULL,
COMPANY_ID INTEGER NOT NULL,
EXPERIENCE_ID INTEGER NOT NULL,
EDUCATION_ID INTEGER NOT NULL,
WORKMODE_ID INTEGER NOT NULL,
STATUS_ID INTEGER,
DATA_DATE DATE,
EXP_DATE DATE NOT NULL,
CONSTRAINT STATUS_ID_FK FOREIGN KEY(STATUS_ID) REFERENCES STATUS(ID),
CONSTRAINT AGE_ID_FK FOREIGN KEY(AGE_ID) REFERENCES AGE(ID),
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID),
CONSTRAINT COMPANY_ID_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(ID),
CONSTRAINT EXPERIENCE_ID_FK FOREIGN KEY(EXPERIENCE_ID) REFERENCES EXPERIENCE(ID),
CONSTRAINT EDUCATION_ID_FK FOREIGN KEY(EDUCATION_ID) REFERENCES EDUCATION(ID),
CONSTRAINT WORKMODE_ID_FK FOREIGN KEY(WORKMODE_ID) REFERENCES WORKMODE(ID)
);


CREATE TABLE MODERATOR(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ACTIVE INTEGER DEFAULT 1
);

INSERT INTO AGE(AGE,ACTIVE) VALUES('18-25',1);
INSERT INTO AGE(AGE,ACTIVE) VALUES('25-35',1);
INSERT INTO AGE(AGE,ACTIVE) VALUES('30-55',1);

INSERT INTO CATEGORY(CATEGORY,ACTIVE) VALUES('Information technology',1);
INSERT INTO CATEGORY(CATEGORY,ACTIVE) VALUES('Design and creativity',1);
INSERT INTO CATEGORY(CATEGORY,ACTIVE) VALUES('Medicine and pharmacy',1);
INSERT INTO CATEGORY(CATEGORY,ACTIVE) VALUES('Training and education',1);

INSERT INTO WORKMODE(WORKMODE,ACTIVE) VALUES('Full time',1);
INSERT INTO WORKMODE(WORKMODE,ACTIVE) VALUES('Part time',1);
INSERT INTO WORKMODE(WORKMODE,ACTIVE) VALUES('Remote',1);
INSERT INTO WORKMODE(WORKMODE,ACTIVE) VALUES('Experience',1);

INSERT INTO EDUCATION(EDUCATION,ACTIVE) VALUES('High school',1);
INSERT INTO EDUCATION(EDUCATION,ACTIVE) VALUES('College/University',1);
INSERT INTO EDUCATION(EDUCATION,ACTIVE) VALUES('Master degree',1);

INSERT INTO EXPERIENCE(EXPERIENCE,ACTIVE) VALUES('Less than 1 year',1);
INSERT INTO EXPERIENCE(EXPERIENCE,ACTIVE) VALUES('1-3 year',1);
INSERT INTO EXPERIENCE(EXPERIENCE,ACTIVE) VALUES('3-5 year',1);
INSERT INTO EXPERIENCE(EXPERIENCE,ACTIVE) VALUES('More than 5 year',1);

INSERT INTO CITY(CITY,ACTIVE) VALUES('Baku',1);
INSERT INTO CITY(CITY,ACTIVE) VALUES('Absheron',1);
INSERT INTO CITY(CITY,ACTIVE) VALUES('Sumghayit',1);
INSERT INTO CITY(CITY,ACTIVE) VALUES('Mingecevir',1);
INSERT INTO CITY(CITY,ACTIVE) VALUES('Gence',1);
INSERT INTO CITY(CITY,ACTIVE) VALUES('Qebele',1);

INSERT INTO STATUS(STATUS,ACTIVE) VALUES("Active",1);
INSERT INTO STATUS(STATUS,ACTIVE) VALUES("Deactive",1);
INSERT INTO STATUS(STATUS,ACTIVE) VALUES("Checking",1);
INSERT INTO STATUS(STATUS,ACTIVE) VALUES("Rejected",1);

INSERT INTO MODERATOR(EMAIL,PASSWORD,ACTIVE) VALUES('moderator@ekadr.az','$2y$10$JGrXBXjKjR3ozrzsprKMLeQYyLcIx8L7hUWik8ab2tXG2Z0ly7Nea',1);
/* moderator mail = moderator@ekadr.az password=$2y$10$JGrXBXjKjR3ozrzsprKMLeQYyLcIx8L7hUWik8ab2tXG2Z0ly7Nea */